# Generated by Django 4.0.4 on 2022-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnES', '0002_mcquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='choice1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='choice2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='choice3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='choice4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
