# Generated by Django 4.0.4 on 2022-05-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnES', '0006_remove_lesson_completion_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
